### ISSUE TITLE
get crash with model You

### ISSUE THREAD

**Issue by huankong233** [xiangsx/gpt4free-ts#1]
the error log here

the strange message is from here,I added into it myself

![image](https://user-images.githubusercontent.com/49610758/236596071-3a66eb4f-df77-4d7e-a9ff-a3a92281df64.png)

~~~
> gpt4free-ts@0.0.1 start
> ts-node index.ts
Now listening: 127.0.0.1:3000

d

d
/usr/src/app/utils/index.ts:27
export function md5(str: string): string {

           ^
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/src/app/model/you/index.ts:138:36
    at /usr/src/app/utils/index.ts:16:13
    at Generator.next (<anonymous>)
    at /usr/src/app/utils/index.ts:31:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/app/utils/index.ts:27:12)
    at /usr/src/app/utils/index.ts:48:16
    at wrappedMapper (/usr/src/app/node_modules/map-stream/index.js:83:19)
    at Stream.stream.write (/usr/src/app/node_modules/map-stream/index.js:95:21)
~~~

**Comment by xiangsx** [comment]
It looks like you.com has adopted some kind of strategy to avoid reverse.

**Comment by xiangsx** [comment]
https://github.com/xtekky/gpt4free/issues/479#issue-1698399164

because of this

**Comment by huankong233** [comment]
thanks

**Comment by xiangsx** [comment]
> the error log here
> 
> the strange message is from here,I added into it myself
> 
> ![image](https://user-images.githubusercontent.com/49610758/236596071-3a66eb4f-df77-4d7e-a9ff-a3a92281df64.png)
> 
> ```
> > gpt4free-ts@0.0.1 start
> > ts-node index.ts
> Now listening: 127.0.0.1:3000
> �
> d
> �
> d
> /usr/src/app/utils/index.ts:27
> export function md5(str: string): string {
> �
>            ^
> SyntaxError: Unexpected token < in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at /usr/src/app/model/you/index.ts:138:36
>     at /usr/src/app/utils/index.ts:16:13
>     at Generator.next (<anonymous>)
>     at /usr/src/app/utils/index.ts:31:71
>     at new Promise (<anonymous>)
>     at __awaiter (/usr/src/app/utils/index.ts:27:12)
>     at /usr/src/app/utils/index.ts:48:16
>     at wrappedMapper (/usr/src/app/node_modules/map-stream/index.js:83:19)
>     at Stream.stream.write (/usr/src/app/node_modules/map-stream/index.js:95:21)
> ```

you can try forefront now, It work


But model for you.com still not work
