### ISSUE TITLE
ffi-napi: Command failed

### ISSUE THREAD

**Issue by engchina** [xiangsx/gpt4free-ts#10]
Hi,

yarn failed on my ubuntu 22.04, the error shows as below. How to solve it?
```
# yarn
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[2/2] ⡀ ffi-napi
error /root/workspace/gpt4free-ts/node_modules/ffi-napi: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments:
Directory: /root/workspace/gpt4free-ts/node_modules/ffi-napi
Output:
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}
```

**Comment by xiangsx** [comment]
> Hi,
> 
> yarn failed on my ubuntu 22.04, the error shows as below. How to solve it?
> ```
> # yarn
> yarn install v1.22.19
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> [3/4] Linking dependencies...
> [4/4] Building fresh packages...
> [2/2] ⡀ ffi-napi
> error /root/workspace/gpt4free-ts/node_modules/ffi-napi: Command failed.
> Exit code: 1
> Command: node-gyp-build
> Arguments:
> Directory: /root/workspace/gpt4free-ts/node_modules/ffi-napi
> Output:
> events.js:291
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn node-gyp EACCES
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
>     at onErrorNT (internal/child_process.js:470:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> Emitted 'error' event on ChildProcess instance at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
>     at onErrorNT (internal/child_process.js:470:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>   errno: 'EACCES',
>   code: 'EACCES',
>   syscall: 'spawn node-gyp',
>   path: 'node-gyp',
>   spawnargs: [ 'rebuild' ]
> }
> ```

update node to v18.x

**Comment by ysh-git-ktc** [comment]
我node升级到了18.16.0,还是一样的错误,怎么办

**Comment by IdaBruce** [comment]
我node升级到了18.16.0,还是一样的错误
