### ISSUE TITLE
an image in Dockerhub

### ISSUE THREAD

**Issue by choogoo** [xiangsx/gpt4free-ts#14]
I created an image in Dockerhub that can be run to use the project.

```
docker run --env rapid_api_key =xxxx atorber/gpt4free-ts:latest
```

**Comment by daguruman** [comment]
i get this error:
Hello! How can I help you today? If you have any questions or need assistance with a task, feel free to ask. SyntaxError: U
nexpected token H in JSON at position 0                                                                                    
    at JSON.parse (<anonymous>)                                                                                            
    at parseJSON (/usr/src/app/utils/index.ts:37:21)                                                                       
    at Forefront.<anonymous> (/usr/src/app/model/forefront/index.ts:80:39)                                                 
    at Generator.next (<anonymous>)                                                                                        
    at /usr/src/app/model/forefront/index.ts:8:71                                                                          
    at new Promise (<anonymous>)                                                                                           
    at __awaiter (/usr/src/app/model/forefront/index.ts:4:12)                                                              
    at /usr/src/app/model/forefront/index.ts:74:93                                                                         
    at wrappedMapper (/usr/src/app/node_modules/map-stream/index.js:83:19)                                                 
    at Stream.stream.write (/usr/src/app/node_modules/map-stream/index.js:95:21)                                           

any ideas?

**Comment by daguruman** [comment]
it worx!  thanx!
