### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by charleshm** [xiangsx/gpt4free-ts#19]
tls-client/dist/sessions.js:44
        this.clientIdentifier = options?.clientIdentifier;
                                        ^

SyntaxError: Unexpected token '.'
    at Object.compileFunction (vm.js:344:18)
    at wrapSafe (internal/modules/cjs/loader.js:1048:15)
    at Module._compile (internal/modules/cjs/loader.js:1082:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Object.require.extensions.<computed> [as .js] (gpt4free-ts/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (gpt4free-ts/node_modules/tls-client/dist/index.js:3:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by fallbort** [comment]
update node to v18.x
