### ISSUE TITLE
Curl test failed

### ISSUE THREAD

**Issue by UncleBigLu** [xiangsx/gpt4free-ts#2]
curl "http://127.0.0.1:3000/ask?prompt=hello"
  AxiosError: Request failed with status code 401
AxiosError: Request failed with status code 401
      at settle (/$HOME/gpt4free-ts/node_modules/axios/lib/core/settle.js:19:12)
      at IncomingMessage.handleStreamEnd (/home/unclebiglu/repostories/gpt4free-ts/node_modules/axios/lib/adapters/http.js:570:11)
      at IncomingMessage.emit (node:events:525:35)
      at IncomingMessage.emit (node:domain:489:12)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)

Internal Server Error

**Comment by xiangsx** [comment]
![image](https://user-images.githubusercontent.com/29322721/236616530-1ea37997-ce9a-497f-b065-24374de54711.png)


have you config this apikey
