### ISSUE TITLE
error existed!

### ISSUE THREAD

**Issue by fallbort** [xiangsx/gpt4free-ts#20]
Error: Failed to create account! sign email res parse token failed!
    at Forefront.<anonymous> (/Users/xx/Workspace/github/gpt4free-ts/model/forefront/index.ts:221:19)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xx/Workspace/github/gpt4free-ts/model/forefront/index.ts:5:58)

**Comment by xiangsx** [comment]
try now, and Post the logs.

I guess your machine has been banned by forefront

**Comment by fallbort** [comment]
Error: Failed to create account! sign email res parse token failed! res:{"errors":[{"message":"Too many requests from this machine. Please try again in a bit.","code":"too_many_requests"}]}
    at Forefront.<anonymous> (/home/ubuntu/src/gpt4free-ts/model/forefront/index.ts:210:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/src/gpt4free-ts/model/forefront/index.ts:5:58)

**Comment by fallbort** [comment]
why

**Comment by fallbort** [comment]
i create a new aws lightsail instance server,then this:

yarn run v1.22.19
$ ts-node index.ts
Now listening: 127.0.0.1:3000
Error: Error while obtaining verfication URL!
    at Forefront.<anonymous> (/home/ubuntu/src/gpt4free-ts/model/forefront/index.ts:231:19
)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/src/gpt4free-ts/model/forefront/index.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
