### ISSUE TITLE
Error: retry again, will sign up again

### ISSUE THREAD

**Issue by malikfalasifa** [xiangsx/gpt4free-ts#22]
Hi. My requests were always rejected by forefront.

- I'm using the latest commit
- Using http proxy
- Changing the UA

```
Error: retry again, will sign up again
    at Forefront.<anonymous> (C:\gpt4free-ts\model\forefront\index.ts:154:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\gpt4free-ts\model\forefront\index.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I'm tracing the exceptions, and it says my request is unauthorized (it was working a few hours ago).

Here is the full exception log (it was too long to put inline here):
https://pastebin.com/XmUWgnRu

**Comment by tilefishpoele** [comment]
they changed x-signature to 128 bit string. maybe sha512 algorithm. you managed to find the parameters last time @xiangsx . any ideas this time?

**Comment by FinnWu** [comment]
Me Too

**Comment by xiangsx** [comment]
I will try to fix it today

**Comment by xchwarze** [comment]
I was stuck in the same thing... I still couldn't find where to put the breakpoint to see how it is calculated....

**Comment by xiangsx** [comment]
I think i has found some solution to fix it. Just wait a little longer

**Comment by tilefishpoele** [comment]
Can you lmk where you found the source code. I might try and fix it too myself. We fixed it together last time :)

**Comment by xiangsx** [comment]
> Can you lmk where you found the source code. I might try and fix it too myself. We fixed it together last time :)

you are that amazing man in discord?

**Comment by IdaBruce** [comment]
you are that amazing man in discord?
