### ISSUE TITLE
Cannot use forefront with status code 401

### ISSUE THREAD

**Issue by HuanLinOTO** [xiangsx/gpt4free-ts#3]
I am in china so I use a US proxy to connect to forefront.ai

this is my log

```
 3.7.9 ⬢  gpt4free-ts ⚡ master ◉ > yarn start
yarn run v1.22.19
$ ts-node index.ts
Now listening: 127.0.0.1:3000

  AxiosError: Request failed with status code 401
      at settle (D:\Project\gpt4free-ts\node_modules\axios\lib\core\settle.js:19:12)
      at IncomingMessage.handleStreamEnd (D:\Project\gpt4free-ts\node_modules\axios\lib\adapters\http.js:570:11)
      at IncomingMessage.emit (node:events:525:35)
      at IncomingMessage.emit (node:domain:489:12)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

I can use forefront by its webui, so I don't think it's a problem by my proxy

![image](https://user-images.githubusercontent.com/94176676/236628109-f6bedf0d-9aa7-47d7-87c8-4b887b589504.png)

It seem that fail on create a temp mail😂

**Comment by HuanLinOTO** [comment]
https://github.com/xiangsx/gpt4free-ts/issues/2

I think I have same problem with this issues, wait for a moment, I'm going to have a try

**Comment by zhuhansan666** [comment]
Correct: In the mainland of Chinese.

**Comment by xiangsx** [comment]
check  rapid_api_key in .env

**Comment by xiangsx** [comment]
> check  rapid_api_key in .env

config this follow readme

**Comment by zhuhansan666** [comment]
怕不是都是中国人（

**Comment by HuanLinOTO** [comment]
好，那我用中文得了）
![image](https://user-images.githubusercontent.com/94176676/236629058-05bd4f9c-1d25-4620-bbfe-d03d212f9d4a.png)


rapidapi 上的 [temp-mail](https://rapidapi.com/Privatix/api/temp-mail/) 是要信用卡的 但是隔壁的 [temp-mail44](https://rapidapi.com/calvinloveland335703-0p6BxLYIH8f/api/temp-mail44) 是硬限制，无需超额付费，请问是否能提供该 API 的调用可选项）

**Comment by xiangsx** [comment]
> 好，那我用中文得了）
> ![image](https://user-images.githubusercontent.com/94176676/236629058-05bd4f9c-1d25-4620-bbfe-d03d212f9d4a.png)
> 
> 
> rapidapi 上的 [temp-mail](https://rapidapi.com/Privatix/api/temp-mail/) 是要信用卡的 但是隔壁的 [temp-mail44](https://rapidapi.com/calvinloveland335703-0p6BxLYIH8f/api/temp-mail44) 是硬限制，无需超额付费，请问是否能提供该 API 的调用可选项）

😂等我回家看看，理论上可以的

**Comment by zhuhansan666** [comment]
理论上来说，由于互联网不分界限(部分国家与地区除外)，所以在互联网上应该先用中文交流，因为使用中文的人数最多（bushi

**Comment by xiangsx** [comment]
> 好，那我用中文得了）
> ![image](https://user-images.githubusercontent.com/94176676/236629058-05bd4f9c-1d25-4620-bbfe-d03d212f9d4a.png)
> 
> 
> rapidapi 上的 [temp-mail](https://rapidapi.com/Privatix/api/temp-mail/) 是要信用卡的 但是隔壁的 [temp-mail44](https://rapidapi.com/calvinloveland335703-0p6BxLYIH8f/api/temp-mail44) 是硬限制，无需超额付费，请问是否能提供该 API 的调用可选项）

你贴的这个不也是rapidapi 吗？这点其实我今天也在考虑看下有没有不需要信用卡的方式，但是一直忙于修复forefront的验证问题

**Comment by HuanLinOTO** [comment]
> > 好，那我用中文得了）
> > ![image](https://user-images.githubusercontent.com/94176676/236629058-05bd4f9c-1d25-4620-bbfe-d03d212f9d4a.png)
> > rapidapi 上的 [temp-mail](https://rapidapi.com/Privatix/api/temp-mail/) 是要信用卡的 但是隔壁的 [temp-mail44](https://rapidapi.com/calvinloveland335703-0p6BxLYIH8f/api/temp-mail44) 是硬限制，无需超额付费，请问是否能提供该 API 的调用可选项）
> 
> 你贴的这个不也是rapidapi 吗？这点其实我今天也在考虑看下有没有不需要信用卡的方式，但是一直忙于修复forefront的验证问题

rapidapi 有些 API 有种付费方式叫做增值付费

就是基础+超额给钱

为了避免你不给钱，需要你绑信用卡自动扣费的

但是有些 API 的付费方式叫做硬限制 超额不给你返回 这些不需要绑信用卡

**Comment by HuanLinOTO** [comment]
![image](https://user-images.githubusercontent.com/94176676/236629453-575a24a3-04c8-4026-8442-78020589b83d.png)

测了 可以使用

**Comment by HuanLinOTO** [comment]
另外可以试试 puppeteer 来自动抓取 token 什么的（

就是对配置要求会比较高，不过这种需求 2c4g 应该都能跑

**Comment by zhuhansan666** [comment]
puppeterr随身wifi跑不了 512Mb+4g 晓龙410（

**Comment by xiangsx** [comment]
> > 你贴的这个不也是rapidapi 吗？这点其实我今天也在考虑看下有没有不需要信用卡的方式，但是一直忙于修复forefront的验证问题
> 
> rapidapi 有些 API 有种付费方式叫做增值付费
> 
> 就是基础+超额给钱
> 
> 为了避免你不给钱，需要你绑信用卡自动扣费的
> 
> 但是有些 API 的付费方式叫做硬限制 超额不给你返回 这些不需要绑信用卡
> 
> ~~另外我未成年，没法办信用卡~~

嗯，看到了，确实不用绑定，晚点会更新一个版本

**Comment by xiangsx** [comment]
https://github.com/xiangsx/gpt4free-ts/commit/3d8d32fc647e834542cedac0c3a3adec173d0bda

has update support tempmail44

not need bind credit

**Comment by HuanLinOTO** [comment]
tempmail44 它的接受和获取都是公用 100 次调用的，很坑，而且响应巨慢

写了个这个 https://github.com/HuanLinOTO/temp-email 可以参考参考

**Comment by zhanghongyong123456** [comment]
> tempmail44 它的接收和获取都是公用的 100 次调用的，很坑，而且反应巨大缓慢
> 
> 写了这个https://github.com/HuanLinOTO/temp-email可以参考参考

大佬，能说说这个怎么用吗，因为不是ts 开发者，所以配置起来很吃力，不知道如何操作，能出一起详细的教学吗
