### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by DNLINYJ** [xiangsx/gpt4free-ts#30]
错误如下 .env的DEBUG无论是0还是1都报相同的错误

root@vps2548886:~/gpt# docker run -p 3000:3000 --env-file .env xiangsx/gpt4free-ts:latest

> gpt4free-ts@0.0.1 start
> ts-node index.ts

browser pool init size:1

  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

Error: Failed to launch the browser process!
[0513/080411.738226:FATAL:zygote_host_impl_linux.cc(127)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.

TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (/usr/src/app/node_modules/@puppeteer/browsers/src/launch.ts:398:11)
    at Interface.emit (node:events:525:35)
    at Interface.emit (node:domain:489:12)
    at Interface.close (node:internal/readline/interface:533:10)
    at Socket.onend (node:internal/readline/interface:259:10)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by DNLINYJ** [comment]
docker-compose up --build 也一样报错

root@vps2548886:~/gpt# rm -rf gpt4free-ts
root@vps2548886:~/gpt# git clone https://github.com/xiangsx/gpt4free-ts.git
Cloning into 'gpt4free-ts'...
remote: Enumerating objects: 326, done.
remote: Counting objects: 100% (129/129), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 326 (delta 100), reused 94 (delta 79), pack-reused 197
Receiving objects: 100% (326/326), 118.99 KiB | 4.76 MiB/s, done.
Resolving deltas: 100% (161/161), done.
root@vps2548886:~/gpt# cp .env gpt4free-ts
root@vps2548886:~/gpt# cd gpt4free-ts
root@vps2548886:~/gpt/gpt4free-ts# ls -a
.  ..  .env  .git  .github  .gitignore  Dockerfile  LICENSE.txt  README.md  docker-compose.yaml  index.ts  model  package.json  pool  tsconfig.json  utils  yarn.lock
root@vps2548886:~/gpt/gpt4free-ts# docker-compose up --build
WARNING: The http_proxy variable is not set. Defaulting to a blank string.
Building gpt4free-ts
[+] Building 218.3s (11/11) FINISHED                                                                                                                                               
 => [internal] load build definition from Dockerfile                                                                                                                          0.2s
 => => transferring dockerfile: 618B                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                             0.4s
 => => transferring context: 2B                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/node:18.16.0                                                                                                               0.8s
 => CACHED [1/6] FROM docker.io/library/node:18.16.0@sha256:3f567a26b6b6d601fb2b168d4f987b50697617ead15bfc0e0152e600ac48d0fe                                                  0.0s
 => [internal] load build context                                                                                                                                             0.7s
 => => transferring context: 314.42kB                                                                                                                                         0.3s
 => [2/6] RUN apt update &&     DEBIAN_FRONTEND=noninteractive apt install -y         libnss3         libatk1.0-0         libatk-bridge2.0-0         libcups2         libdr  39.8s
 => [3/6] WORKDIR /usr/src/app                                                                                                                                                1.6s
 => [4/6] COPY --chown=1000 package.json /usr/src/app/                                                                                                                        1.1s 
 => [5/6] RUN npm i --registry=https://registry.npm.taobao.org                                                                                                               72.2s 
 => [6/6] COPY --chown=1000 . /usr/src/app                                                                                                                                    1.9s 
 => exporting to image                                                                                                                                                       99.1s 
 => => exporting layers                                                                                                                                                      99.0s 
 => => writing image sha256:f6ed4b9de0499e84a39b6228a31f2c85770401f52ace3285987ff049c4f73ff8                                                                                  0.0s 
 => => naming to docker.io/library/gpt4free-ts:latest                                                                                                                         0.1s 
Recreating gpt4free-ts ... done
Attaching to gpt4free-ts
gpt4free-ts    | 
gpt4free-ts    | > gpt4free-ts@0.0.1 start
gpt4free-ts    | > ts-node index.ts
gpt4free-ts    | 
gpt4free-ts    | browser pool init size:1
gpt4free-ts    | Error: Failed to launch the browser process! undefined
gpt4free-ts    | [33:53:0513/081219.114709:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
gpt4free-ts    | [33:33:0513/081220.039060:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
gpt4free-ts    | [33:33:0513/081220.039175:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
gpt4free-ts    | 
gpt4free-ts    | 
gpt4free-ts    | TROUBLESHOOTING: https://pptr.dev/troubleshooting
gpt4free-ts    | 
gpt4free-ts    |     at ChildProcess.onClose (/usr/src/app/node_modules/@puppeteer/browsers/src/launch.ts:398:11)
gpt4free-ts    |     at ChildProcess.emit (node:events:525:35)
gpt4free-ts    |     at ChildProcess.emit (node:domain:489:12)
gpt4free-ts    |     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gpt4free-ts    | 
gpt4free-ts    | > gpt4free-ts@0.0.1 start
gpt4free-ts    | > ts-node index.ts
gpt4free-ts    | 
gpt4free-ts    | browser pool init size:1
gpt4free-ts    | Error: Failed to launch the browser process! undefined
gpt4free-ts    | [33:52:0513/081232.028776:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
gpt4free-ts    | [33:33:0513/081232.039478:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
gpt4free-ts    | [33:33:0513/081232.039517:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
gpt4free-ts    | 
gpt4free-ts    | 
gpt4free-ts    | TROUBLESHOOTING: https://pptr.dev/troubleshooting
gpt4free-ts    | 
gpt4free-ts    |     at ChildProcess.onClose (/usr/src/app/node_modules/@puppeteer/browsers/src/launch.ts:398:11)
gpt4free-ts    |     at ChildProcess.emit (node:events:525:35)
gpt4free-ts    |     at ChildProcess.emit (node:domain:489:12)
gpt4free-ts    |     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gpt4free-ts exited with code 1
gpt4free-ts    | 
gpt4free-ts    | > gpt4free-ts@0.0.1 start
gpt4free-ts    | > ts-node index.ts
gpt4free-ts    | 
gpt4free-ts    | browser pool init size:1
gpt4free-ts    | Error: Failed to launch the browser process! undefined
gpt4free-ts    | [33:33:0513/081242.787605:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
gpt4free-ts    | [33:33:0513/081242.789648:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
gpt4free-ts    | [33:52:0513/081242.791208:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
gpt4free-ts    | 
gpt4free-ts    | 
gpt4free-ts    | TROUBLESHOOTING: https://pptr.dev/troubleshooting
gpt4free-ts    | 
gpt4free-ts    |     at ChildProcess.onClose (/usr/src/app/node_modules/@puppeteer/browsers/src/launch.ts:398:11)
gpt4free-ts    |     at ChildProcess.emit (node:events:525:35)
gpt4free-ts    |     at ChildProcess.emit (node:domain:489:12)
gpt4free-ts    |     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gpt4free-ts exited with code 1
gpt4free-ts    | 
gpt4free-ts    | > gpt4free-ts@0.0.1 start
gpt4free-ts    | > ts-node index.ts
gpt4free-ts    | 
gpt4free-ts    | browser pool init size:1
gpt4free-ts    | Error: Failed to launch the browser process! undefined
gpt4free-ts    | [33:52:0513/081253.290378:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
gpt4free-ts    | [33:33:0513/081253.306254:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
gpt4free-ts    | [33:33:0513/081253.306306:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
gpt4free-ts    | 
gpt4free-ts    | 
gpt4free-ts    | TROUBLESHOOTING: https://pptr.dev/troubleshooting
gpt4free-ts    | 
gpt4free-ts    |     at ChildProcess.onClose (/usr/src/app/node_modules/@puppeteer/browsers/src/launch.ts:398:11)
gpt4free-ts    |     at ChildProcess.emit (node:events:525:35)
gpt4free-ts    |     at ChildProcess.emit (node:domain:489:12)
gpt4free-ts    |     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gpt4free-ts exited with code 1
root@vps2548886:~/gpt/gpt4free-ts# docker ps
CONTAINER ID   IMAGE                COMMAND                  CREATED              STATUS         PORTS                                       NAMES
66ebe7374989   gpt4free-ts:latest   "docker-entrypoint.s…"   About a minute ago   Up 2 seconds   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   gpt4free-ts
c9de8eba51b7   img_gpt4free         "streamlit run strea…"   6 days ago           Up 6 days      0.0.0.0:8501->8501/tcp, :::8501->8501/tcp   dc_gpt4free
root@vps2548886:~/gpt/gpt4free-ts# docker ps
CONTAINER ID   IMAGE                COMMAND                  CREATED              STATUS                                  PORTS                                       NAMES
66ebe7374989   gpt4free-ts:latest   "docker-entrypoint.s…"   About a minute ago   Restarting (1) Less than a second ago                                               gpt4free-ts
c9de8eba51b7   img_gpt4free         "streamlit run strea…"   6 days ago           Up 6 days                               0.0.0.0:8501->8501/tcp, :::8501->8501/tcp   dc_gpt4free
root@vps2548886:~/gpt/gpt4free-ts# docker stop gpt4free-ts
gpt4free-ts

**Comment by xiangsx** [comment]
#32
