### ISSUE TITLE
请问一下有arm版本的镜像吗？

### ISSUE THREAD

**Issue by Alex-Joe-Lee** [xiangsx/gpt4free-ts#44]
请问一下有arm版本的镜像吗？

**Comment by ZevaXu** [comment]
能否根据dockerfile文件自己在arm机器上编译呢

**Comment by xiangsx** [comment]
你可以试试

**Comment by ZevaXu** [comment]
试了不行，`npm i` 那行报错了，`exec /bin/sh: exec format error`

**Comment by ZevaXu** [comment]
在amd机器上部署后测试
`curl "http://127.0.0.1:13000/ask/stream?prompt=hello&model=forefront&gptmodel=gpt-4&resignup=1"`
报错
`event: error
data: "please wait init.....about 1 min"`
是不是forefront也不给用了

**Comment by xiangsx** [comment]
看下控制台日志

**Comment by JacquelineLena** [comment]
你可以试试

**Comment by GitSarp** [comment]
> 能否根据dockerfile文件自己在arm机器上编译呢

Dockerfile修改了基础镜像：

**Comment by GitSarp** [comment]
> 能否根据dockerfile文件自己在arm机器上编译呢

我修改了基础镜像, 可以构建出arm64的镜像：
`
#FROM ghcr.io/puppeteer/puppeteer:20.5.0
FROM exileed/puppeteer:node-latest
#FROM nestosoftware/puppeteer:16.16.0-3

USER root

WORKDIR /usr/src/app

COPY --chown=pptruser package.json /usr/src/app/

#RUN npm i --registry=https://registry.npm.taobao.org
RUN npm i 

COPY --chown=pptruser . /usr/src/app

VOLUME [ "/usr/src/app/run" ]

EXPOSE 3000

CMD npm start
`
但是启动还是报错：
`
> gpt4free-ts@0.0.1 start
> ts-node index.ts
Error: Cannot find module 'puppeteer-extra'
Require stack:
- /usr/src/app/pool/puppeteer.ts
- /usr/src/app/model/phind/index.ts
- /usr/src/app/model/index.ts
- /usr/src/app/index.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/usr/src/app/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:866:27)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/usr/src/app/pool/puppeteer.ts:7:19)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Module.m._compile (/usr/src/app/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/src/app/node_modules/ts-node/src/index.ts:1621:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/pool/puppeteer.ts',
    '/usr/src/app/model/phind/index.ts',
    '/usr/src/app/model/index.ts',
    '/usr/src/app/index.ts'
  ]
}
`

**Comment by xiangsx** [comment]
> > 能否根据dockerfile文件自己在arm机器上编译呢
> 
> 我修改了基础镜像, 可以构建出arm64的镜像： ` #FROM ghcr.io/puppeteer/puppeteer:20.5.0 FROM exileed/puppeteer:node-latest #FROM nestosoftware/puppeteer:16.16.0-3
> 
> USER root
> 
> WORKDIR /usr/src/app
> 
> COPY --chown=pptruser package.json /usr/src/app/
> 
> #RUN npm i --registry=https://registry.npm.taobao.org RUN npm i
> 
> COPY --chown=pptruser . /usr/src/app
> 
> VOLUME [ "/usr/src/app/run" ]
> 
> EXPOSE 3000
> 
> CMD npm start `但是启动还是报错：`
> 
> > gpt4free-ts@0.0.1 start
> > ts-node index.ts
> > Error: Cannot find module 'puppeteer-extra'
> > Require stack:
> 
> * /usr/src/app/pool/puppeteer.ts
> * /usr/src/app/model/phind/index.ts
> * /usr/src/app/model/index.ts
> * /usr/src/app/index.ts
>   at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
>   at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/usr/src/app/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
>   at Function.Module._load (node:internal/modules/cjs/loader:866:27)
>   at Module.require (node:internal/modules/cjs/loader:1093:19)
>   at require (node:internal/modules/cjs/helpers:108:18)
>   at Object. (/usr/src/app/pool/puppeteer.ts:7:19)
>   at Module._compile (node:internal/modules/cjs/loader:1191:14)
>   at Module.m._compile (/usr/src/app/node_modules/ts-node/src/index.ts:1618:23)
>   at Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
>   at Object.require.extensions. [as .ts] (/usr/src/app/node_modules/ts-node/src/index.ts:1621:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   '/usr/src/app/pool/puppeteer.ts',
>   '/usr/src/app/model/phind/index.ts',
>   '/usr/src/app/model/index.ts',
>   '/usr/src/app/index.ts'
>   ]
>   }
>   `

Retry latest code, And Could you make pr if it worked

**Comment by GitSarp** [comment]
> > > 能否根据dockerfile文件自己在arm机器上编译呢
> > 
> > 
> > 我修改了基础镜像, 可以构建出arm64的镜像： ` #FROM ghcr.io/puppeteer/puppeteer:20.5.0 FROM exileed/puppeteer:node-latest #FROM nestosoftware/puppeteer:16.16.0-3
> > USER root
> > WORKDIR /usr/src/app
> > COPY --chown=pptruser package.json /usr/src/app/
> > #RUN npm i --registry=https://registry.npm.taobao.org RUN npm i
> > COPY --chown=pptruser . /usr/src/app
> > VOLUME [ "/usr/src/app/run" ]
> > EXPOSE 3000
> > CMD npm start `但是启动还是报错：`
> > > gpt4free-ts@0.0.1 start
> > > ts-node index.ts
> > > Error: Cannot find module 'puppeteer-extra'
> > > Require stack:
> > 
> > 
> > 
> > * /usr/src/app/pool/puppeteer.ts
> > * /usr/src/app/model/phind/index.ts
> > * /usr/src/app/model/index.ts
> > * /usr/src/app/index.ts
> >   at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
> >   at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/usr/src/app/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
> >   at Function.Module._load (node:internal/modules/cjs/loader:866:27)
> >   at Module.require (node:internal/modules/cjs/loader:1093:19)
> >   at require (node:internal/modules/cjs/helpers:108:18)
> >   at Object. (/usr/src/app/pool/puppeteer.ts:7:19)
> >   at Module._compile (node:internal/modules/cjs/loader:1191:14)
> >   at Module.m._compile (/usr/src/app/node_modules/ts-node/src/index.ts:1618:23)
> >   at Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
> >   at Object.require.extensions. [as .ts] (/usr/src/app/node_modules/ts-node/src/index.ts:1621:12) {
> >   code: 'MODULE_NOT_FOUND',
> >   requireStack: [
> >   '/usr/src/app/pool/puppeteer.ts',
> >   '/usr/src/app/model/phind/index.ts',
> >   '/usr/src/app/model/index.ts',
> >   '/usr/src/app/index.ts'
> >   ]
> >   }
> >   `
> 
> Retry latest code, And Could you make pr if it worked

可以启动了，浏览器无法init,我试下另外的基础镜像
> gpt4free-ts@0.0.1 start
> ts-node index.ts
Now listening: 127.0.0.1:3000
init one failed, err: Error: Failed to launch the browser process!
/root/.cache/puppeteer/chrome/linux-114.0.5735.90/chrome-linux64/chrome: 1: /root/.cache/puppeteer/chrome/linux-114.0.5735.90/chrome-linux64/chrome: Syntax error: "(" unexpected
TROUBLESHOOTING: https://pptr.dev/troubleshooting
    at Interface.onClose (/usr/src/app/node_modules/@puppeteer/browsers/src/launch.ts:398:11)
    at Interface.emit (node:events:525:35)
    at Interface.emit (node:domain:489:12)
    at Interface.close (node:readline:590:8)
    at Socket.onend (node:readline:280:10)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
init cae58b41-b7c6-44fa-9395-58dad8b7d73e failed, delete! init new ed5c20cd-1ee3-4322-b4f6-b81ba00970b9
init one failed, err: Error: Failed to launch the browser process! undefined
TROUBLESHOOTING: https://pptr.dev/troubleshooting
    at ChildProcess.onClose (/usr/src/app/node_modules/@puppeteer/browsers/src/launch.ts:398:11)

**Comment by GitSarp** [comment]
基于0.43版本构建的arm64镜像可用了,不过这个地方一直报超时:
init one failed, err: TimeoutError: Waiting for selector `div > .mt-4 > div > .form-check > .form-check-label` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (/usr/src/app/node_modules/puppeteer-core/src/common/WaitTask.ts:92:11)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
init ea093797-98a1-441f-9566-873783e0bdcf failed, delete! init new 29c63427-997f-4982-8d18-733aebab32de
180b34a1-d157-4342-b464-6541466e2fcb has been deleted
init one failed, err: TimeoutError: Waiting for selector `div > .mt-4 > div > .form-check > .form-check-label` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (/usr/src/app/node_modules/puppeteer-core/src/common/WaitTask.ts:92:11)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
init 72ad9f4c-7e59-4e54-b898-7edcc9c9cbb2 failed, delete! init new 943ee885-c216-43d6-850d-001ca2bfae5a
ea093797-98a1-441f-9566-873783e0bdcf has been deleted

附dockfile_arm64：
FROM node:18-bookworm

USER root
WORKDIR /usr/src/app

RUN apt-get update && apt-get install make gcc g++ ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils -y

RUN apt-get update && apt-get install -yq chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

COPY --chown=pptruser package.json /usr/src/app/
#RUN npm config set unsafe-perm true
RUN npm i 
RUN npm i puppeteer --save

COPY --chown=pptruser . /usr/src/app

VOLUME [ "/usr/src/app/run" ]

EXPOSE 3000

CMD npm start

**Comment by befantasy** [comment]
有后续进展吗？ARM用户期待。。。
