### ISSUE TITLE
这是什么问题

### ISSUE THREAD

**Issue by 1152588263** [xiangsx/gpt4free-ts#57]
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Mcbbs.<anonymous> (C:\Users\admin\Desktop\gpt4free-ts-master\model\mcbbs\index.ts:68:28)
    at Generator.next (<anonymous>)
    at C:\Users\\admin\Desktop\gpt4free-ts-master\model\mcbbs\index.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\\admin\Desktop\gpt4free-ts-master\model\mcbbs\index.ts:4:12)
    at Mcbbs.askStream (C:\Users\\admin\Desktop\gpt4free-ts-master\model\mcbbs\index.ts:49:16)
    at Mcbbs.<anonymous> (C:\Users\\admin\Desktop\gpt4free-ts-master\model\mcbbs\index.ts:46:32)
    at Generator.next (<anonymous>)
    at C:\Users\\admin\Desktop\gpt4free-ts-master\model\mcbbs\index.ts:8:71
something error happened,err: Error: Error while obtaining verfication URL!
    at Forefrontnew.<anonymous> (C:\Users\\admin\Desktop\gpt4free-ts-master\model\forefront\index.ts:253:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\\admin\Desktop\gpt4free-ts-master\model\forefront\index.ts:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
init 0a57d7b6-1342-43a0-9d35-eeaf0383133a failed, delete! init new 5d5e38b9-0241-4442-9f9e-2c2ec281a04c
(node:30728) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
something error happened,err: Error: Error while obtaining verfication URL!
    at Forefrontnew.<anonymous> (C:\Users\11525\Desktop\gpt4free-ts-master\model\forefront\index.ts:253:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\\admin\Desktop\gpt4free-ts-master\model\forefront\index.ts:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
init 5d5e38b9-0241-4442-9f9e-2c2ec281a04c failed, delete! init new ceb4d3a6-0a7c-442f-bb56-7f663294e92e

**Comment by med214-02** [comment]
nice

**Comment by xiangsx** [comment]
try now

**Comment by ElvaWalton** [comment]
try now

**Comment by ZacharyCroft** [comment]
try now

**Comment by MartinMelville** [comment]
try

**Comment by LeonardBarton** [comment]
try now

**Comment by kazimics** [comment]
Same problem
