### ISSUE TITLE
Yarn Start Faild

### ISSUE THREAD

**Issue by MarvinV28** [xiangsx/gpt4free-ts#7]
When I try to start the program with Yarn I get the error:

/gpt4free-ts# yarn start
yarn run v1.22.19
$ ts-node index.ts
/gpt4free-ts/node_modules/tls-client/dist/sessions.js:44
        this.clientIdentifier = options?.clientIdentifier;
                                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .js] (/var/docker/gpt4free-ts/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/docker/gpt4free-ts/node_modules/tls-client/dist/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
error Command failed with exit code 1.

**Comment by xiangsx** [comment]
node 啥版本，用18.x
