### ISSUE TITLE
佬们，启动报错了，怎么办

### ISSUE THREAD

**Issue by ikimiler** [xiangsx/gpt4free-ts#73]
mijiangbo@mideMacBook-Pro gpt4free-ts % yarn start
yarn run v1.22.19
warning ../../package.json: No license field
$ ts-node index.ts
Now listening: 127.0.0.1:3000
init one failed, err: ProtocolError: Waiting for selector `div > .mt-4 > div > .form-check > .form-check-label` failed: Protocol error (Runtime.callFunctionOn): Target closed
    at new Callback (/Users/mijiangbo/Downloads/gpt4free-ts/node_modules/puppeteer-core/src/common/Connection.ts:65:12)
    at CallbackRegistry.create (/Users/mijiangbo/Downloads/gpt4free-ts/node_modules/puppeteer-core/src/common/Connection.ts:126:22)
    at Connection._rawSend (/Users/mijiangbo/Downloads/gpt4free-ts/node_modules/puppeteer-core/src/common/Connection.ts:266:22)
    at CDPSessionImpl.send (/Users/mijiangbo/Downloads/gpt4free-ts/node_modules/puppeteer-core/src/common/Connection.ts:525:29)
    at ExecutionContext._ExecutionContext_evaluate (/Users/mijiangbo/Downloads/gpt4free-ts/node_modules/puppeteer-core/src/common/ExecutionContext.ts:305:44)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CDPJSHandle.evaluateHandle (/Users/mijiangbo/Downloads/gpt4free-ts/node_modules/puppeteer-core/src/common/JSHandle.ts:87:12)
    at async WaitTask.rerun (/Users/mijiangbo/Downloads/gpt4free-ts/node_modules/puppeteer-core/src/common/WaitTask.ts:159:22)
init f475221a-27a0-4c3f-94ff-5d2fb0b91b0d failed, delete! init new e3ba784c-34e0-42c2-86dc-ca642374ece2
f475221a-27a0-4c3f-94ff-5d2fb0b91b0d has been deleted
init one failed, err: ProtocolError: Waiting for selector `div > .mt-4 > div > .form-check > .form-check-label` failed: Protocol error (Runtime.callFunctionOn): Target closed
    at new Callback (/Users/mijiangbo/Downloads/gpt4free-ts/node_modules/puppeteer-core/src/common/Connection.ts:65:12)
    at CallbackRegistry.create (/Users/mijiangbo/Downloads/gpt4free-ts/node_modules/puppeteer-core/src/common/Connection.ts:126:22)
    at Connection._rawSend (/Users/mijiangbo/Downloads/gpt4free-ts/node_modules/puppeteer-core/src/common/Connection.ts:266:22)
    at CDPSessionImpl.send (/Users/mijiangbo/Downloads/gpt4free-ts/node_modules/puppeteer-core/src/common/Connection.ts:525:29)
    at ExecutionContext._ExecutionContext_evaluate (/Users/mijiangbo/Downloads/gpt4free-ts/node_modules/puppeteer-core/src/common/ExecutionContext.ts:305:44)

**Comment by richardzhangy26** [comment]
xd，我arm的mac好像也不行，得换一个

**Comment by ikimiler** [comment]
> xd，我arm的mac好像也不行，得换一个

ok
