### ISSUE TITLE
sealos Cloud版启动失败

### ISSUE THREAD

**Issue by TuanZiGit** [xiangsx/gpt4free-ts#76]
这是我的项目中1号节点的日志
```
> gpt4free-ts@0.0.1 start
> ts-node index.ts

Now listening: 127.0.0.1:3000
init one failed, err: Error: Failed to launch the browser process! undefined
[37:61:0626/104600.999582:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[37:37:0626/104601.122878:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
[37:37:0626/104601.122977:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/usr/src/app/node_modules/@puppeteer/browsers/src/launch.ts:398:11)
    at ChildProcess.emit (node:events:525:35)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
init 471b4ba6-43ea-4f72-abe3-330a2f2bcc3b failed, delete! init new e7d21caf-96dd-4460-9944-21264bb1ec52
init one failed, err: Error: Failed to launch the browser process!
[38:80:0626/104601.099409:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[38:38:0626/104601.149851:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
[38:38:0626/104601.149889:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
[0626/104601.161629:ERROR:nacl_helper_linux.cc(355)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (/usr/src/app/node_modules/@puppeteer/browsers/src/launch.ts:398:11)
    at Interface.emit (node:events:525:35)
    at Interface.emit (node:domain:489:12)
    at Interface.close (node:internal/readline/interface:533:10)
    at Socket.onend (node:internal/readline/interface:259:10)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
init d70babdf-09bf-4216-a033-374794c93aac failed, delete! init new cdfa73d4-3a47-41bc-8a39-58522ecd4f3f
471b4ba6-43ea-4f72-abe3-330a2f2bcc3b has been deleted
d70babdf-09bf-4216-a033-374794c93aac has been deleted
init one failed, err: Error: Failed to launch the browser process! undefined
[47:92:0626/104601.153097:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[47:47:0626/104601.191310:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
[47:47:0626/104601.191354:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/usr/src/app/node_modules/@puppeteer/browsers/src/launch.ts:398:11)
    at ChildProcess.emit (node:events:525:35)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
init de034842-588a-44a5-9438-f83bc5bcd7fc failed, delete! init new 2c3e7eea-2397-4ed7-92f5-99b1605965ec
de034842-588a-44a5-9438-f83bc5bcd7fc has been deleted
```

这是service.yml
``` yaml
apiVersion: v1
kind: Service
metadata:
  name: freegpt4
  labels:
    cloud.sealos.io/app-deploy-manager: freegpt4
spec:
  ports:
    - port: 3000
  selector:
    app: freegpt4
```

这是statefulSet.yml
``` yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freegpt4
  annotations:
    originImageName: xiangsx/gpt4free-ts:latest
    deploy.cloud.sealos.io/minReplicas: '3'
    deploy.cloud.sealos.io/maxReplicas: '3'
  labels:
    cloud.sealos.io/app-deploy-manager: freegpt4
    app: freegpt4
spec:
  replicas: 3
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: freegpt4
  selector:
    matchLabels:
      app: freegpt4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: freegpt4
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: freegpt4
          image: xiangsx/gpt4free-ts:latest
          env:
            - name: rapid_api_key
              value: 1486ad92cemshf4017d1039e13bap14e590jsn9daa57e20f63
            - name: DEBUG
              value: '1'
            - name: POOL_SIZE
              value: '5'
            - name: EMAIL_TYPE
              value: temp_mail
            - name: PHIND_POOL_SIZE
              value: '3'
          resources:
            requests:
              cpu: 200m
              memory: 102Mi
            limits:
              cpu: 2000m
              memory: 1024Mi
          command: []
          args: []
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          volumeMounts:
            - name: vn-usrvn-srcvn-appvn-run
              mountPath: /usr/src/app/run
      volumes: []
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /usr/src/app/run
          value: '1'
        name: vn-usrvn-srcvn-appvn-run
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
```

这是ingress.yml
``` yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freegpt4
  labels:
    cloud.sealos.io/app-deploy-manager: freegpt4
    cloud.sealos.io/app-deploy-manager-domain: abrfuuehrjpr
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: fgpt.lixiaotuan.cn
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: freegpt4
                port:
                  number: 3000
  tls:
    - hosts:
        - fgpt.lixiaotuan.cn
      secretName: freegpt4

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: freegpt4
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@sealos.io
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: freegpt4
spec:
  secretName: freegpt4
  dnsNames:
    - fgpt.lixiaotuan.cn
  issuerRef:
    name: freegpt4
    kind: Issuer
```

**Comment by wang3lei22** [comment]
兄弟，解决了么~？
我也有类似的问题
