### ISSUE TITLE
Init Failed

### ISSUE THREAD

**Issue by taynotfound** [xiangsx/gpt4free-ts#78]
```
init one failed, err: TimeoutError: Waiting for selector `div > .mt-4 > div > .form-check > .form-check-label` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (/home/tay/gpt4free-ts/node_modules/puppeteer-core/src/common/WaitTask.ts:91:11)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
init b1ebbf9d-0d33-43de-a189-2b9f0b28cb40 failed, delete! init new 4f5e6a6e-eb28-4367-9bde-aaa2ab9302ef

```

On Debian 11. Via Yarn

**Comment by taynotfound** [comment]
Plus it uses so much CPU and RAM every time it tries todo that.

**Comment by xiangsx** [comment]
try v0.0.49

**Comment by taynotfound** [comment]
> try v0.0.49

Of what?

**Comment by taynotfound** [comment]
nvm found

**Comment by xiangsx** [comment]
docker image

**Comment by taynotfound** [comment]
Yea, i am running off of the Source, But yea after pulling it doesnt consume that much CPU or RAM anymore. Phind still does not work tho.

**Comment by xiangsx** [comment]
ok  i try to fix it

**Comment by taynotfound** [comment]
Forefront gives me this error btw:
`

error:"not support site: forefront "
`

**Comment by taynotfound** [comment]
And the Memory Leak still happens. Its using up more than 1 GB. 


8|GPT4FREE  | (node:1962021) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
8|GPT4FREE  | (Use `node --trace-warnings ...` to show where the warning was created)
8|GPT4FREE  | init one failed, err: TimeoutError: Waiting for selector `div > .mt-4 > div > .form-check > .form-check-label` failed: Waiting failed: 30000ms exceeded
8|GPT4FREE  |     at Timeout.<anonymous> (/home/tay/gpt4free-ts/node_modules/puppeteer-core/src/common/WaitTask.ts:91:11)
8|GPT4FREE  |     at listOnTimeout (node:internal/timers:564:17)
8|GPT4FREE  |     at processTimers (node:internal/timers:507:7)
8|GPT4FREE  | init 2d1d3e29-082a-4ff9-ae75-16e9f1d8e0df failed, delete! init new 932052a4-48dc-42cd-8d6a-ef2791bd9de0
8|GPT4FREE  | 2d1d3e29-082a-4ff9-ae75-16e9f1d8e0df has been deleted
8|GPT4FREE  | (node:1962021) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
8|GPT4FREE  | (node:1962021) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit
8|GPT4FREE  | (node:1962021) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added to [process]. Use emitter.setMaxListeners() to increase limit

**Comment by xiangsx** [comment]
pull and retry

**Comment by taynotfound** [comment]
Still the exact same issue

**Comment by xiangsx** [comment]
Show me the log

**Comment by xiangsx** [comment]
It appears that your device cannot access the PHIND 

if you can access phind directly , delete http_proxy in `.env`

**Comment by taynotfound** [comment]
> It appears that your device cannot access the PHIND
> 
> if you can access phind directly , delete http_proxy in `.env`

How can i access PHIND?

**Comment by taynotfound** [comment]
I am so confused. For what is the http proxy?

**Comment by taynotfound** [comment]
After 40 mins it hat 100% CPU and 95% RAM

**Comment by taynotfound** [comment]
PHIND still in initing but i dont care. Finally turned off the PHIND pool.

**Comment by xiangsx** [comment]
if you dont use phind    set phind_pool_size=0

**Comment by taynotfound** [comment]
Yea, did that. Its best now
