### ISSUE TITLE
i used Run with docker but open ip:3000  shows"Not Found"

### ISSUE THREAD

**Issue by MackDing** [xiangsx/gpt4free-ts#92]
![image](https://github.com/xiangsx/gpt4free-ts/assets/19878893/7816ad5f-bfaf-496d-8268-9beff147d2ac)

[root@localhost mack]# vim .env
[root@localhost mack]# docker run -p 3000:3000 --env-file .env xiangsx/gpt4free-ts:latest
Now listening: 127.0.0.1:3000
init one failed, err: TimeoutError: Waiting for selector `.mb-3 > div > div > .mt-6 > .btn-primary` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:71:37)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
init 4e3d37d4-595c-4aeb-acb0-59e3f6f590ab failed, delete! init new 94f8dbd5-66c6-4e3e-a3a0-7e43189a0715
4e3d37d4-595c-4aeb-acb0-59e3f6f590ab has been deleted
init one failed, err: TimeoutError: Waiting for selector `.mb-3 > div > div > .mt-6 > .btn-primary` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:71:37)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
init 94f8dbd5-66c6-4e3e-a3a0-7e43189a0715 failed, delete! init new d5ec3c6f-837c-4acb-b762-9ef26a1abd1b
94f8dbd5-66c6-4e3e-a3a0-7e43189a0715 has been deleted
init one failed, err: TimeoutError: Waiting for selector `.mb-3 > div > div > .mt-6 > .btn-primary` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:71:37)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
init d5ec3c6f-837c-4acb-b762-9ef26a1abd1b failed, delete! init new 34803073-a9b9-4cb1-8de3-d5a6c6e25bdd
d5ec3c6f-837c-4acb-b762-9ef26a1abd1b has been deleted

**Comment by frankzzw** [comment]
.env没配
